# Generated by Django 3.0.6 on 2020-05-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('status', models.CharField(choices=[('base', 'Обычный'), ('vip', 'VIP')], default='base', max_length=20)),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cleaner', 'Служба уборки'), ('parking', 'Парковка'), ('reception', 'Рецепция'), ('cooker', 'Ресторан'), ('tour_guide', 'Экскурсовод')], max_length=255)),
                ('occupation', models.CharField(max_length=255, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена услуги')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название услуги')),
                ('text', models.TextField(default='', verbose_name='Описание услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название номера')),
                ('count_seats', models.IntegerField(blank=True, default=2, null=True, verbose_name='Кол-во мест')),
                ('description', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='Описание')),
                ('view_from_window', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Вид из окна')),
                ('rate', models.IntegerField(blank=True, default=5, null=True)),
                ('price', models.FloatField(verbose_name='Цена номера')),
                ('services', models.ManyToManyField(to='back_office.Service', verbose_name='Услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='female', max_length=255, verbose_name='Пол')),
                ('salary', models.FloatField(verbose_name='ЗП')),
                ('type', models.CharField(choices=[('back', 'BACK'), ('front', 'FRONT')], max_length=255, verbose_name='Back или Front Office')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_office.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата заезда')),
                ('date_to', models.DateField(verbose_name='Дата выезда')),
                ('total_price', models.FloatField(blank=True, default=0, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_office.Client')),
                ('optional_services', models.ManyToManyField(to='back_office.Service')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_office.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Паспортные данные')),
                ('money', models.FloatField(verbose_name='Сколько денег оставили перед вьездом')),
                ('order', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_office.Order')),
            ],
        ),
    ]
