# Generated by Django 3.0.6 on 2020-05-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_now', models.DateTimeField(auto_now_add=True)),
                ('date_when', models.DateTimeField(verbose_name='На когда это сделать')),
                ('date_done', models.DateTimeField(verbose_name='Когда сделано')),
                ('msg', models.TextField(blank=True, default='', max_length=2555, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Статус заявки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_office.Client')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_office.Booking')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_office.Service')),
                ('who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back_office.Personal')),
            ],
        ),
    ]
